### ISSUE TITLE
Uncaught TypeError: Cannot read property 'end' of undefined

### ISSUE THREAD

**Issue by mwager** [mattbryson/TouchSwipe-Jquery-Plugin#215]
Did you ever experience such an issue?

We have an app running in production and this error gets thrown a lot.

Search the [source file](https://github.com/mattbryson/TouchSwipe-Jquery-Plugin/blob/master/jquery.touchSwipe.js) for `".end"` - maybe you could introduce more checks for existence?

Our main problem is this leads to __lots__ of logs sent to our servers :-(

Additional info:
* Android phones running inside cordova
* UA: _Mozilla/5.0 (Linux; Android 4.4.2; SM-G900F Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36_

**Comment by tobemedia** [comment]
I can reproduce this using a iPhone or iPad. 

Error message is a bit different: 
UNCAUGHT ERROR: TypeError: undefined is not an object (evaluating 'c.end') file

The problem seems to be incorrect or unset coordinates used to calculate the swipe in some cases.

UserAgent:
Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B466 Safari/600.1.4

**Comment by mwager** [comment]
We decided to use a patched version now, maybe you could take a look: https://github.com/mwager/TouchSwipe-Jquery-Plugin/commit/ca974b6e7f958817eb55a1130ff69eb8f93c1eb8

**Comment by mattbryson** [comment]
Cool, thanks, I'll check it out.
