### ISSUE TITLE
Range Input not working

### ISSUE THREAD

**Issue by JohnScottMcNerney** [mattbryson/TouchSwipe-Jquery-Plugin#289]
Version 1.6.18
jquery-1.10.2.min.js

A range input (i.e. "input type='range'") does not work. This works with version 1.6.12. Clicking and dragging the input slider will cause a swipe, and the input slider will not change. Seems like the 'touch' on the input slider is not being passed down to it.

I'm only using swipeLeft and swipeRight, isolated in a very simple test case.

$("#rng").on('input change',function(e){e.stopPropagation();$("#debug").prepend("Range Change<br>");});
$("#box").swipe({
swipeLeft:function(event, direction, distance, duration, fingerCount,fingerData) { $("#debug").prepend("Swipe Left<br>"); }
swipeRight:function(event, direction, distance, duration, fingerCount,fingerData) { $("#debug").prepend("Swipe Right<br>"); }
});

**Comment by JohnScottMcNerney** [comment]
Digging through the source code, I found that swipes are ignored on elements with a "class='noSwipe'". This did make the input range work again.

I tried to find reference to this in the documentation, but was not successful.

**Comment by mattbryson** [comment]
The docs re excluded items are here;

http://labs.rampinteractive.co.uk/touchSwipe/demos/Excluded_children.html

and the default values listed here…

http://labs.rampinteractive.co.uk/touchSwipe/docs/$.fn.swipe.defaults.html

Its not massively clear in the JS docs  - not sure if they is a way to
promote that somehow...

-- 
Matt Bryson


On 8 June 2016 at 13:41:08, JohnScottMcNerney (notifications@github.com)
wrote:

Digging through the source code, I found that swipes are ignored on
elements with a "class='noSwipe'". This did make the input range work again.

I tried to find reference to this in the documentation, but was not
successful.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mattbryson/TouchSwipe-Jquery-Plugin/issues/289#issuecomment-224576649>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAhgVJqLyMRqXBSFW_w_nD9RPWfT1bWnks5qJrhkgaJpZM4IwC5j>
.
