### ISSUE TITLE
Scrolling down causes swipe left or right

### ISSUE THREAD

**Issue by howardowens** [mattbryson/TouchSwipe-Jquery-Plugin#319]
I'm using TouchSwipe to enable swiping between content sections on my app.

Here's my implementation:
```  $("body").swipe( {
      swipeRight:function(event, direction, distance, duration, fingerCount) {
        window.open("index.html?s=news");
      },
      swipeLeft:function(event, direction, distance, duration, fingerCount) {
        window.open("index.html?s=business");
      },
        threshold:200
    });
```
Works fine for swiping, but if I'm scrolling down the page, even though the swipe is clearly down, the section will jump to the left or right section.  No matter how straight I try to move my finger straight down, as soon as the scroll stops, the page jumps.

How do I fix this?

**Comment by howardowens** [comment]
I seem to have answered my own question with this.

http://labs.rampinteractive.co.uk/touchSwipe/demos/Page_scrolling.html

**Comment by woutervanwijk** [comment]
I do have this problem too, even while setting allowPageScroll. I tested a bit. In the fingerData[0], I presume that for the start.y and end.y the scroll position is not taken into account. So if I scroll up, the delta abs of end.y - start.y is almost nothing, because the end.y has scrolled along with the page. TouchSwipe should probably correct for the scroll position?

**Comment by mattbryson** [comment]
Closing as over a year old.  Please feel free to re open if you are still having issues.
