### ISSUE TITLE
How to change swipe position when image clicked ?

### ISSUE THREAD

**Issue by ebatgerel** [mattbryson/TouchSwipe-Jquery-Plugin#338]
I am currently working on image gallery.  I need to do when i click image swipe position change based on image position. How to do it ? i am stuck with this problem. Any solution ?

**Comment by mattbryson** [comment]
Sorry, I don’t understand the issue.  Do you have a plunker or jsfiddle
showing the issue?

-- 
Matt Bryson


On 23 January 2018 at 06:47:32, Batgerel Enkhbat (notifications@github.com)
wrote:

I am currently working on image gallery. I need to do when i click image
swipe position change based on image position. How to do it ? i am stuck
with this problem. Any solution ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mattbryson/TouchSwipe-Jquery-Plugin/issues/338>, or mute
the thread
